### ISSUE TITLE
.NET Identity is a noob framework

### ISSUE THREAD

**Issue by ianbro** [BudgetSquirrel/BudgetTracker#30]
Sooooo .NET identity forces you into this dumb service injection crap. It requires you to pass it the model you will use and the signinasync function attemps to sign you into a session (which we are not doing). It's great if you're a noob sheep and want to blindly follow what they force you to do, but we are not that!

So, create a library that does not introduce state. No dependency injection crap!

**Comment by BenjaminGroseclose** [comment]
Wait you hate DI?
