### ISSUE TITLE
Sub-budgets creation take on parents duration

### ISSUE THREAD

**Issue by ianbro** [BudgetSquirrel/BudgetTracker#61]
Story: #60 

When creating a Sub-budget, the duration should be ignored. Instead, it should automatically take on the duration of it's parent.

**Comment by BenjaminGroseclose** [comment]
Feel like this is almost two part story.
- We should have a place in the UI to prevent users from setting the sub budget duration 
- And we should auto set it based on the parent duration in the backend.

I think this story is best suited to be set up the backend and I will create a story that will be for the front end.

**Comment by ianbro** [comment]
I agree it should be broken down (technically this is a task since it's technical, not user oriented and the others are sub-tasks). However, we don't need to add anything to the UI. Actually, we can just take the form away for sub-budgets. So rather than that "Add to UI to restrict", we just modify the story that allows user to change the duration of a budget so that they only modify the root budget duration.

**Comment by BenjaminGroseclose** [comment]
Sounds good if you want to close out #71 until we start the UI we can do that.
