### ISSUE TITLE
Modifying budget duration should cascade to sub-budgets.

### ISSUE THREAD

**Issue by ianbro** [BudgetSquirrel/BudgetTracker#62]
Story: #60 

When modifying a budget's duration, all sub-budgets should reflect those changes and have their durations modified. This is recursive of course so all those sub-budgets should also cascade.

Only root budgets may have their duration modified. So add validation for this as well.

**Comment by BenjaminGroseclose** [comment]
We will have to figure out how to allow them to have different durations with sub budgets.

**Comment by ianbro** [comment]
Well, I don't think they should be able to. That wouldn't really make sense. The point of a sub-budget is to break down it's parent into smaller chunks. So how do you calculate balance if the date windows are different.
