### ISSUE TITLE
Change Budget Duration

### ISSUE THREAD

**Issue by ianbro** [BudgetSquirrel/BudgetTracker#7]
As a Budget Planner, I should be able to change the Duration and Duration Unit on a Master Budget so that I can plan for a different type of budget.

Master Budget: The top most (root) budget in a tree of budgets. This budget does not have any parent budgets.

A user may not alter budgets Duration or Duration Unit which have a parent budget. They can only modify a Master Budget.

When a user modifies a Master Budget, all of it's sub-budgets (whether direct children or children of children recursively) should inherit the changes. This should be recursive.

**Comment by BenjaminGroseclose** [comment]
@ianbro Believe this is complete by UpdateBudget

**Comment by ianbro** [comment]
Yessir it is
