### ISSUE TITLE
Make Sub-Budget into a Master Budget

### ISSUE THREAD

**Issue by ianbro** [BudgetSquirrel/BudgetTracker#8]
As a Budget Planner, I should be able to take a sub-budget at any level in the budget tree and make it a root budget for it's own tree so that I can organize my budgets better.

Basically, this simply means you remove the budget from the tree and it's parents list of sub-budgets. It still has it's own sub-budgets, but it becomes the Master Budget for it's sub-budgets. Of course, this implies that a user may have more than one Master Budgets as this would make this budget a Master Budget.

**Comment by BenjaminGroseclose** [comment]
@ianbro Would this be as simple as removing the ParentId?

**Comment by ianbro** [comment]
Yeah. But you also need to copy the duration into a separate object. It will be the same values, but both the original tree and this new one have to have their own duration object.

**Comment by BenjaminGroseclose** [comment]
This can already be handled by our method in the API. Would simply be a Create new root budget with the same data and delete the old one from the other root budget.
